//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibraryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Authors> Authors { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<Countries> Countries { get; set; }
    
        public virtual ObjectResult<Books> method1ReturnBooks(Nullable<int> pageCount)
        {
            var pageCountParameter = pageCount.HasValue ?
                new ObjectParameter("pageCount", pageCount) :
                new ObjectParameter("pageCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method1ReturnBooks", pageCountParameter);
        }
    
        public virtual ObjectResult<Books> method1ReturnBooks(Nullable<int> pageCount, MergeOption mergeOption)
        {
            var pageCountParameter = pageCount.HasValue ?
                new ObjectParameter("pageCount", pageCount) :
                new ObjectParameter("pageCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method1ReturnBooks", mergeOption, pageCountParameter);
        }
    
        public virtual ObjectResult<Books> method2ReturnBooks(string letter)
        {
            var letterParameter = letter != null ?
                new ObjectParameter("letter", letter) :
                new ObjectParameter("letter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method2ReturnBooks", letterParameter);
        }
    
        public virtual ObjectResult<Books> method2ReturnBooks(string letter, MergeOption mergeOption)
        {
            var letterParameter = letter != null ?
                new ObjectParameter("letter", letter) :
                new ObjectParameter("letter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method2ReturnBooks", mergeOption, letterParameter);
        }
    
        public virtual ObjectResult<Books> method3ReturnsBooks(string name, string surname)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method3ReturnsBooks", nameParameter, surnameParameter);
        }
    
        public virtual ObjectResult<Books> method3ReturnsBooks(string name, string surname, MergeOption mergeOption)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method3ReturnsBooks", mergeOption, nameParameter, surnameParameter);
        }
    
        public virtual ObjectResult<Books> method4ReturnBooks(string countryName)
        {
            var countryNameParameter = countryName != null ?
                new ObjectParameter("countryName", countryName) :
                new ObjectParameter("countryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method4ReturnBooks", countryNameParameter);
        }
    
        public virtual ObjectResult<Books> method4ReturnBooks(string countryName, MergeOption mergeOption)
        {
            var countryNameParameter = countryName != null ?
                new ObjectParameter("countryName", countryName) :
                new ObjectParameter("countryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method4ReturnBooks", mergeOption, countryNameParameter);
        }
    
        public virtual ObjectResult<Books> method5ReturnBooks(Nullable<int> nameLenght)
        {
            var nameLenghtParameter = nameLenght.HasValue ?
                new ObjectParameter("nameLenght", nameLenght) :
                new ObjectParameter("nameLenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method5ReturnBooks", nameLenghtParameter);
        }
    
        public virtual ObjectResult<Books> method5ReturnBooks(Nullable<int> nameLenght, MergeOption mergeOption)
        {
            var nameLenghtParameter = nameLenght.HasValue ?
                new ObjectParameter("nameLenght", nameLenght) :
                new ObjectParameter("nameLenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method5ReturnBooks", mergeOption, nameLenghtParameter);
        }
    
        public virtual ObjectResult<Books> method6ReturnBooks(string countryName)
        {
            var countryNameParameter = countryName != null ?
                new ObjectParameter("countryName", countryName) :
                new ObjectParameter("countryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method6ReturnBooks", countryNameParameter);
        }
    
        public virtual ObjectResult<Books> method6ReturnBooks(string countryName, MergeOption mergeOption)
        {
            var countryNameParameter = countryName != null ?
                new ObjectParameter("countryName", countryName) :
                new ObjectParameter("countryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Books>("method6ReturnBooks", mergeOption, countryNameParameter);
        }
    
        public virtual ObjectResult<Authors> method7ReturnAuthor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Authors>("method7ReturnAuthor");
        }
    
        public virtual ObjectResult<Authors> method7ReturnAuthor(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Authors>("method7ReturnAuthor", mergeOption);
        }
    
        public virtual ObjectResult<Countries> method8ReturnCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Countries>("method8ReturnCountry");
        }
    
        public virtual ObjectResult<Countries> method8ReturnCountry(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Countries>("method8ReturnCountry", mergeOption);
        }
    }
}
